namespace GLAZOV.M.TRANSLATE.Providers.Baidu;

/// <summary>
/// Represents the identity of an application registered on the Baidu Translate
/// open platform, which every Baidu request is made on behalf of.
/// </summary>
/// <remarks>
/// <para>
/// Unlike the other providers of this library, Baidu offers no keyless
/// endpoint: its web page guards translation with a token generated by the
/// browser, so the only supported way in is the official open platform
/// (<c>fanyi-api.baidu.com</c>), which gives every developer an application
/// identifier and a secret key.
/// </para>
/// <para>
/// The secret key is never exposed: it is not a public property and never
/// appears in <see cref="ToString"/>. Instances are immutable and thread-safe.
/// </para>
/// </remarks>
public sealed class BaiduCredentials
{
    /// <summary>
    /// Gets the identifier of the application.
    /// </summary>
    public string AppId { get; }

    /// <summary>
    /// Gets the secret key of the application, for the signing of requests.
    /// </summary>
    internal string SecretKey { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="BaiduCredentials"/> class.
    /// </summary>
    /// <param name="appId">
    /// The identifier of the application.
    /// </param>
    /// <param name="secretKey">
    /// The secret key of the application.
    /// </param>
    /// <exception cref="ArgumentNullException">
    /// Thrown when <paramref name="appId"/> or <paramref name="secretKey"/> is
    /// <see langword="null"/>.
    /// </exception>
    /// <exception cref="ArgumentException">
    /// Thrown when <paramref name="appId"/> or <paramref name="secretKey"/> is
    /// empty or consists only of white-space characters.
    /// </exception>
    public BaiduCredentials(string appId, string secretKey)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(appId);
        ArgumentException.ThrowIfNullOrWhiteSpace(secretKey);

        AppId = appId.Trim();
        SecretKey = secretKey.Trim();
    }

    /// <inheritdoc/>
    public override string ToString()
    {
        return $"{nameof(BaiduCredentials)} {{ AppId = {AppId} }}";
    }
}
