using GLAZOV.M.TRANSLATE.Domain.Linguistics.Languages;
using GLAZOV.M.TRANSLATE.Domain.Linguistics.Languages.Codes;
using GLAZOV.M.TRANSLATE.Providers.Google.Internal;
using System.Net;
using System.Text;

namespace GLAZOV.M.TRANSLATE.Providers.Google.Generator;

/// <summary>
/// One-shot code generator that asks the Google speech endpoint, language by
/// language, which of them it can speak, and writes the generated
/// <c>GoogleSpeechLanguages.g.cs</c> the text-to-speech provider checks a
/// request against.
/// </summary>
/// <remarks>
/// <para>
/// The endpoint publishes no list of its own: it answers 200 for a language
/// it speaks and 400 for one it does not, so the list can only be found by
/// asking. Every language of the registry that has an ISO 639-1 code is
/// asked once.
/// </para>
/// <para>
/// This is a dev-time tool, not shipped with the library. Re-run it whenever
/// the list needs to be refreshed.
/// </para>
/// </remarks>
internal static class Program
{
    private const string Endpoint = "https://translate.google.com/translate_tts";

    private const string Probe = "test";

    // The endpoint starts refusing a caller that asks too quickly.
    private static readonly TimeSpan BetweenRequests = TimeSpan.FromMilliseconds(300);

    private static readonly string ProviderRoot = Path.GetFullPath(
        Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "src", "GLAZOV.M.TRANSLATE.Providers.Google"));

    private static async Task Main()
    {
        using HttpClient httpClient = new();

        List<string> spoken = [];
        List<string> silent = [];

        foreach (Language language in LanguageRegistry.Default.All)
        {
            if (!language.Codes.TryGetValue(out Iso6391Code? code))
            {
                continue;
            }

            string googleCode = GoogleLanguageCodeResolver.ToGoogleCode(language.Id);

            bool speaks = await SpeaksAsync(httpClient, googleCode);

            (speaks ? spoken : silent).Add(code.Value);

            Console.WriteLine($"{code.Value,-4} {googleCode,-6} {(speaks ? "speaks" : "silent")}");

            await Task.Delay(BetweenRequests);
        }

        string path = Path.Combine(ProviderRoot, "Internal", "GoogleSpeechLanguages.g.cs");

        File.WriteAllText(path, Generate(spoken), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        Console.WriteLine($"{spoken.Count} spoken, {silent.Count} silent -> {path}");
    }

    private static async Task<bool> SpeaksAsync(HttpClient httpClient, string googleCode)
    {
        string token = GoogleTokenGenerator.Generate(Probe);

        Uri uri = new($"{Endpoint}?ie=UTF-8&q={Probe}&tl={Uri.EscapeDataString(googleCode)}" +
                      $"&ttsspeed=1&total=1&idx=0&client=tw-ob&textlen={Probe.Length}" +
                      $"&tk={Uri.EscapeDataString(token)}");

        for (int attempt = 0; attempt < 3; attempt++)
        {
            using HttpResponseMessage response = await httpClient.GetAsync(uri);

            if (response.StatusCode == HttpStatusCode.OK)
            {
                return true;
            }

            if (response.StatusCode == HttpStatusCode.BadRequest)
            {
                return false;
            }

            // Anything else - a rate limit, a hiccup - is not an answer about
            // the language, so it is asked again.
            await Task.Delay(TimeSpan.FromSeconds(2));
        }

        throw new InvalidOperationException($"The endpoint never answered about '{googleCode}'.");
    }

    private static string Generate(List<string> spoken)
    {
        StringBuilder builder = new();

        builder.AppendLine("// <auto-generated>");
        builder.AppendLine("// Generated by tools/GLAZOV.M.TRANSLATE.Providers.Google.Generator. Do not edit by hand.");
        builder.AppendLine("// </auto-generated>");
        builder.AppendLine();
        builder.AppendLine("using System.Collections.Immutable;");
        builder.AppendLine();
        builder.AppendLine("namespace GLAZOV.M.TRANSLATE.Providers.Google.Internal;");
        builder.AppendLine();
        builder.AppendLine("internal static partial class GoogleSpeechLanguages");
        builder.AppendLine("{");
        builder.AppendLine("    // ISO 639-1 codes of the languages the endpoint answered for when asked.");
        builder.AppendLine("    private static readonly ImmutableHashSet<string> Spoken =");
        builder.AppendLine("        ImmutableHashSet.Create(StringComparer.Ordinal,");

        foreach (string[] line in spoken.Order(StringComparer.Ordinal).Chunk(12))
        {
            builder.AppendLine($"            {string.Join(", ", line.Select(code => $"\"{code}\""))},");
        }

        builder.Length -= Environment.NewLine.Length + 1;
        builder.AppendLine(");");
        builder.AppendLine("}");

        return builder.ToString();
    }
}
