// <auto-generated>
// Generated by tools/GLAZOV.M.TRANSLATE.Providers.Google.Generator. Do not edit by hand.
// </auto-generated>

using System.Collections.Immutable;

namespace GLAZOV.M.TRANSLATE.Providers.Google.Internal;

internal static partial class GoogleSpeechLanguages
{
    // ISO 639-1 codes of the languages the endpoint answered for when asked.
    private static readonly ImmutableHashSet<string> Spoken =
        ImmutableHashSet.Create(StringComparer.Ordinal,
            "af", "am", "ar", "bg", "bn", "bs", "ca", "cs", "cy", "da", "de", "el",
            "en", "es", "et", "eu", "fi", "fr", "gl", "gu", "ha", "he", "hi", "hr",
            "hu", "id", "is", "it", "ja", "jv", "km", "kn", "ko", "la", "lt", "lv",
            "ml", "mr", "ms", "my", "nb", "ne", "nl", "no", "pa", "pl", "pt", "ro",
            "ru", "si", "sk", "sq", "sr", "su", "sv", "sw", "ta", "te", "th", "tr",
            "uk", "ur", "vi", "zh");
}
