// <auto-generated>
// Generated by tools/GLTranslate.Providers.Microsoft.Generator. Do not edit by hand.
// </auto-generated>

using System.Collections.Immutable;

namespace GLTranslate.Providers.Microsoft.Internal;

internal static partial class MicrosoftVoices
{
    // Keyed by ISO 639-1 code. The value is the voice the speech endpoint
    // speaks that language with unless the caller names another one.
    private static readonly ImmutableDictionary<string, string> DefaultByIso6391 =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["af"] = "af-ZA-AdriNeural", // Afrikaans (South Africa)
            ["am"] = "am-ET-MekdesNeural", // Amharic (Ethiopia)
            ["ar"] = "ar-SA-ZariyahNeural", // Arabic (Saudi Arabia)
            ["as"] = "as-IN-YashicaNeural", // Assamese (India)
            ["az"] = "az-AZ-BanuNeural", // Azerbaijani (Latin, Azerbaijan)
            ["bg"] = "bg-BG-KalinaNeural", // Bulgarian (Bulgaria)
            ["bn"] = "bn-BD-NabanitaNeural", // Bangla (Bangladesh)
            ["bs"] = "bs-BA-VesnaNeural", // Bosnian (Bosnia and Herzegovina)
            ["ca"] = "ca-ES-JoanaNeural", // Catalan
            ["cs"] = "cs-CZ-VlastaNeural", // Czech (Czechia)
            ["cy"] = "cy-GB-NiaNeural", // Welsh (United Kingdom)
            ["da"] = "da-DK-ChristelNeural", // Danish (Denmark)
            ["de"] = "de-DE-SeraphinaMultilingualNeural", // German (Germany)
            ["el"] = "el-GR-AthinaNeural", // Greek (Greece)
            ["en"] = "en-US-AvaMultilingualNeural", // English (United States)
            ["es"] = "es-ES-ElviraNeural", // Spanish (Spain)
            ["et"] = "et-EE-AnuNeural", // Estonian (Estonia)
            ["eu"] = "eu-ES-AinhoaNeural", // Basque
            ["fa"] = "fa-IR-DilaraNeural", // Persian (Iran)
            ["fi"] = "fi-FI-SelmaNeural", // Finnish (Finland)
            ["fil"] = "fil-PH-BlessicaNeural", // Filipino (Philippines)
            ["fr"] = "fr-FR-DeniseNeural", // French (France)
            ["ga"] = "ga-IE-OrlaNeural", // Irish (Ireland)
            ["gl"] = "gl-ES-SabelaNeural", // Galician
            ["gu"] = "gu-IN-DhwaniNeural", // Gujarati (India)
            ["he"] = "he-IL-HilaNeural", // Hebrew (Israel)
            ["hi"] = "hi-IN-AaravNeural", // Hindi (India)
            ["hr"] = "hr-HR-GabrijelaNeural", // Croatian (Croatia)
            ["hu"] = "hu-HU-NoemiNeural", // Hungarian (Hungary)
            ["hy"] = "hy-AM-AnahitNeural", // Armenian (Armenia)
            ["id"] = "id-ID-GadisNeural", // Indonesian (Indonesia)
            ["is"] = "is-IS-GudrunNeural", // Icelandic (Iceland)
            ["it"] = "it-IT-ElsaNeural", // Italian (Italy)
            ["iu"] = "iu-Cans-CA-SiqiniqNeural", // Inuktitut (Syllabics, Canada)
            ["ja"] = "ja-JP-NanamiNeural", // Japanese (Japan)
            ["jv"] = "jv-ID-SitiNeural", // Javanese (Latin, Indonesia)
            ["ka"] = "ka-GE-EkaNeural", // Georgian (Georgia)
            ["kk"] = "kk-KZ-AigulNeural", // Kazakh (Kazakhstan)
            ["km"] = "km-KH-SreymomNeural", // Khmer (Cambodia)
            ["kn"] = "kn-IN-SapnaNeural", // Kannada (India)
            ["ko"] = "ko-KR-SunHiNeural", // Korean (Korea)
            ["lo"] = "lo-LA-KeomanyNeural", // Lao (Laos)
            ["lt"] = "lt-LT-OnaNeural", // Lithuanian (Lithuania)
            ["lv"] = "lv-LV-EveritaNeural", // Latvian (Latvia)
            ["mk"] = "mk-MK-MarijaNeural", // Macedonian (North Macedonia)
            ["ml"] = "ml-IN-SobhanaNeural", // Malayalam (India)
            ["mn"] = "mn-MN-YesuiNeural", // Mongolian (Mongolia)
            ["mr"] = "mr-IN-AarohiNeural", // Marathi (India)
            ["ms"] = "ms-MY-YasminNeural", // Malay (Malaysia)
            ["mt"] = "mt-MT-GraceNeural", // Maltese (Malta)
            ["my"] = "my-MM-NilarNeural", // Burmese (Myanmar)
            ["nb"] = "nb-NO-PernilleNeural", // Norwegian Bokmål (Norway)
            ["ne"] = "ne-NP-HemkalaNeural", // Nepali (Nepal)
            ["nl"] = "nl-NL-FennaNeural", // Dutch (Netherlands)
            ["or"] = "or-IN-SubhasiniNeural", // Odia (India)
            ["pa"] = "pa-IN-OjasNeural", // Punjabi (India)
            ["pl"] = "pl-PL-AgnieszkaNeural", // Polish (Poland)
            ["ps"] = "ps-AF-LatifaNeural", // Pashto (Afghanistan)
            ["pt"] = "pt-BR-FranciscaNeural", // Portuguese (Brazil)
            ["ro"] = "ro-RO-AlinaNeural", // Romanian (Romania)
            ["ru"] = "ru-RU-SvetlanaNeural", // Russian (Russia)
            ["si"] = "si-LK-ThiliniNeural", // Sinhala (Sri Lanka)
            ["sk"] = "sk-SK-ViktoriaNeural", // Slovak (Slovakia)
            ["sl"] = "sl-SI-PetraNeural", // Slovenian (Slovenia)
            ["so"] = "so-SO-UbaxNeural", // Somali (Somalia)
            ["sq"] = "sq-AL-AnilaNeural", // Albanian (Albania)
            ["sr"] = "sr-Latn-RS-NicholasNeural", // Serbian (Latin, Serbia)
            ["su"] = "su-ID-TutiNeural", // Sundanese (Indonesia)
            ["sv"] = "sv-SE-SofieNeural", // Swedish (Sweden)
            ["sw"] = "sw-KE-ZuriNeural", // Swahili (Kenya)
            ["ta"] = "ta-IN-PallaviNeural", // Tamil (India)
            ["te"] = "te-IN-ShrutiNeural", // Telugu (India)
            ["th"] = "th-TH-PremwadeeNeural", // Thai (Thailand)
            ["tr"] = "tr-TR-EmelNeural", // Turkish (Türkiye)
            ["uk"] = "uk-UA-PolinaNeural", // Ukrainian (Ukraine)
            ["ur"] = "ur-PK-UzmaNeural", // Urdu (Pakistan)
            ["uz"] = "uz-UZ-MadinaNeural", // Uzbek (Latin, Uzbekistan)
            ["vi"] = "vi-VN-HoaiMyNeural", // Vietnamese (Vietnam)
            ["wuu"] = "wuu-CN-XiaotongNeural", // Chinese (Wu, Simplified)
            ["yue"] = "yue-CN-XiaoMinNeural", // Chinese (Cantonese, Simplified)
            ["zh"] = "zh-CN-XiaoxiaoNeural", // Chinese (Mandarin, Simplified)
            ["zu"] = "zu-ZA-ThandoNeural", // Zulu (South Africa)
        }.ToImmutableDictionary();
}
